services:
  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: casahaven-app
    container_name: casahaven-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker_configs/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - casahaven-network
    depends_on:
      - db

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: casahaven-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker_configs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_configs/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - casahaven-network
    depends_on:
      - app

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: casahaven-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: casahaven
      MYSQL_ROOT_PASSWORD: bechir
      MYSQL_PASSWORD: bechir
      MYSQL_USER: bechir
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - casahaven-network

# Networks
networks:
  casahaven-network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
